### ISSUE TITLE
Zone gets wrongly disabled after volume creation error due to mistaken user input

### ISSUE THREAD

**Issue by emiran-orange** [Excelero/nvmesh-csi-driver#35]
The zone is disabled whatever the error (https://github.com/Excelero/nvmesh-csi-driver/blob/master/driver/controller_service.py#L155).

In case of a mistaken user input (like `spec.resources.requests.storage` lower than 1GB), the volume creation fails:
```
NVMeshSDK - DEBUG - url https://OFUSCATED:4000/volumes/save got response: Received incorrect REST request! Error: data.body[0].capacity should be >= 1000000000, data.body[0].capacity should be equal to constant, data.body[0].capacity should be equal to constant, data.body[0].capacity should match some schema in anyOf, data.body should match "then" schema
...
topology - WARNING - disabled_zones: zone OFUSCATED disabled
```
This should not happen as no other volume can be created afterwards until controller pod is restarted

**Comment by gil-excelero** [comment]
Resolved by: 0e00bfd45ab36a416278e2eff2eaff4c93e93827

**Comment by emiran-orange** [comment]
@gil-excelero Thx for the fix. Any chance version 1.2.1 could be released now ?

**Comment by emiran-orange** [comment]
> @gil-excelero Thx for the fix. Any chance version 1.2.1 could be released now ?

Actually this hould for #37 to be fixed
